import { test, expect } from '@playwright/test';
const path = '/tests/starting-areas/index.html';
test.beforeEach(async ({ page }) => {
  // No live Supabase, routes, CDN resources or map tiles are allowed.
  await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
});
test('admin creates, renames, repositions, retries and deletes an area; visitor uses its saved origin', async ({ page }) => {
  await page.goto(path);
  await expect(page.getByTestId('row-starting-area-centre')).toBeVisible();
  await page.getByTestId('button-add-starting-area').click();
  await page.getByTestId('input-starting-area-name').fill('Station square');
  await page.getByTestId('input-starting-area-lat').fill('91');
  await page.getByTestId('input-starting-area-lon').fill('-4.258');
  await page.getByTestId('button-save-starting-area').click();
  await expect(page.getByTestId('input-starting-area-lat')).toHaveAttribute('aria-invalid', 'true');
  await page.getByTestId('input-starting-area-lat').fill('55.859');
  await page.evaluate(() => { window.areaFixture.fail = 'save'; });
  await page.getByTestId('button-save-starting-area').click();
  await expect(page.getByTestId('status-starting-area-save-error')).toBeVisible();
  await expect(page.getByTestId('input-starting-area-name')).toHaveValue('Station square');
  await page.getByTestId('button-save-starting-area').click();
  await expect(page.getByTestId('status-starting-area-note')).toContainText('was added');
  const id = await page.evaluate(() => window.areaFixture.rows.find(row => row.name === 'Station square').id);
  await page.getByTestId(`button-edit-starting-area-${id}`).click();
  await page.getByTestId('input-starting-area-name').fill('Central station');
  await page.getByTestId('input-starting-area-lat').fill('55.8595');
  await page.getByTestId('button-save-starting-area').click();
  await expect(page.getByTestId('status-starting-area-note')).toContainText('was updated');
  await page.goto(path + '?view=visitor');
  await page.getByTestId('button-mode-nearby').click();
  await page.getByTestId(`button-start-${id}`).click();
  await page.getByTestId('button-plan-route').click();
  await expect(page.getByTestId('result-plan')).toBeVisible();
  expect(await page.evaluate(() => window.areaFixture.origin)).toEqual({ lat: 55.8595, lon: -4.258 });
  await page.goto(path);
  await page.getByTestId(`button-delete-starting-area-${id}`).click();
  await expect(page.getByTestId('dialog-delete-starting-area')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByTestId('dialog-delete-starting-area')).toBeHidden();
  await page.getByTestId(`button-delete-starting-area-${id}`).click();
  await page.evaluate(() => { window.areaFixture.fail = 'delete'; });
  await page.getByTestId('button-confirm-delete-starting-area').click();
  await expect(page.getByTestId('status-delete-starting-area-error')).toBeVisible();
  await page.getByTestId('button-confirm-delete-starting-area').click();
  await expect(page.getByTestId(`row-starting-area-${id}`)).toBeHidden();
  await page.goto(path + '?view=visitor');
  await page.getByTestId('button-mode-nearby').click();
  await expect(page.getByTestId(`button-start-${id}`)).toHaveCount(0);
  await expect(page.getByTestId('button-start-gps')).toBeVisible();
});
test('visitor keeps empty/error states honest, can retry, and never requests GPS for a removed saved point', async ({ page }) => {
  await page.goto(path + '?view=visitor');
  await page.getByTestId('button-mode-nearby').click();
  await page.getByTestId('button-start-centre').click();
  await page.evaluate(() => { window.areaFixture.rows = []; });
  await page.getByTestId('button-plan-route').click();
  await expect(page.getByTestId('status-planner-error')).toContainText('no longer available');
  await page.evaluate(() => { window.areaFixture.fail = 'read'; window.dispatchEvent(new Event('focus')); });
  await expect(page.getByTestId('status-starting-areas-error')).toBeVisible();
  await page.getByRole('button', { name: 'Retry starting points' }).click();
  await expect(page.getByText('No saved starting points are available.')).toBeVisible();
  await expect(page.getByTestId('button-start-centre')).toHaveCount(0);
  await expect(page.getByTestId('button-plan-route')).toBeDisabled();
  await page.getByTestId('button-start-gps').click();
  await expect(page.getByTestId('button-plan-route')).toBeEnabled();
});
test('mobile admin can keep unsaved changes, cancel deletion with keyboard, and recover a list failure', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(path);
  await page.getByTestId('button-edit-starting-area-centre').click();
  await page.getByTestId('input-starting-area-name').fill('Edited centre');
  await page.getByTestId('button-cancel-starting-area').click();
  await expect(page.getByTestId('dialog-discard-starting-area')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByTestId('input-starting-area-name')).toHaveValue('Edited centre');
  await page.getByTestId('button-cancel-starting-area').click();
  await page.getByTestId('button-confirm-discard-starting-area').click();
  await page.getByTestId('button-delete-starting-area-centre').click();
  await page.keyboard.press('Tab');
  await page.keyboard.press('Tab');
  await expect(page.getByTestId('button-cancel-delete-starting-area')).toBeFocused();
  await page.keyboard.press('Escape');
  await page.evaluate(() => { window.areaFixture.fail = 'read'; });
  await page.getByTestId('button-refresh-starting-areas').click();
  await expect(page.getByTestId('status-starting-areas-error')).toBeVisible();
  await page.getByTestId('button-retry-starting-areas').click();
  await expect(page.getByTestId('status-starting-areas-error')).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});